### ISSUE TITLE
Unfortunately, I do not accept pull requests from 15 year olds with cropped yiff pfps.

### ISSUE THREAD

**Issue by httpget** [LuaCoding/LuaCoding#2]
unfortunately interpreterk is a 17 year old with a headshot of his fursona for a pfp
the above statement completely invalidates your entire shitspeak

i have an issue with you haivng the audacity to call me a retard then getting us mixed up
personally i would've just said no

              Unfortunately, I do not accept pull requests from 15 year olds with cropped yiff pfps.

_Originally posted by @LuaCoding in https://github.com/LuaCoding/LuaCoding/issues/1#issuecomment-1439315167_

**Comment by LuaCoding** [comment]
cry
